# Generated by Django 5.0.7 on 2024-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
